version: '3.7'
services:
     
  category-api:
    image: mydockercont2020/category-api
    build:
      context: ./category-api
      dockerfile: Dockerfile
    ports:
      - "8181:8080"
    networks:
      - eservices-sqlserver
    depends_on:
      - SQLServer 

  brand-api:
    image: mydockercont2020/brand-api
    build:
      context: ./brand-api
      dockerfile: Dockerfile
    ports:
      - "8182:8080"
    networks:
      - eservices-sqlserver
    depends_on:
      - SQLServer

  product-api:
    image: mydockercont2020/product-api
    build:
      context: ./product-api
      dockerfile: Dockerfile
    ports:
      - "8183:8080"
    networks:
      - eservices-sqlserver
    depends_on:
      - SQLServer
      
  subcategoryapi:
    image: mydockercont2020/subcategoryapi
    build:
      context: ./DotNetServices/subcategoryapi
      dockerfile: Dockerfile
    ports:
      - "8184:80"
    networks:
      - eservices-sqlserver

  SQLServer:
    container_name: SQLServer
    image: microsoft/mssql-server-windows-developer
    networks:
      - eservices-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DockerDB2020   
      - attach_dbs=[{'dbName':'UserDB','dbFiles':['C:\\JavaAndDocker\\DockerDB\\SQLData\\UserDB.mdf','C:\\JavaAndDocker\\DockerDB\\SQLData\\UserDB_log.ldf']},{'dbName':'CategoryDB','dbFiles':['C:\\JavaAndDocker\\DockerDB\\SQLData\\CategoryDB.mdf','C:\\JavaAndDocker\\DockerDB\\SQLData\\CategoryDB_log.ldf']},{'dbName':'SubCategoryDB','dbFiles':['C:\\JavaAndDocker\\DockerDB\\SQLData\\SubCategoryDB.mdf','C:\\JavaAndDocker\\DockerDB\\SQLData\\SubCategoryDB_log.ldf']},{'dbName':'BrandDB','dbFiles':['C:\\JavaAndDocker\\DockerDB\\SQLData\\BrandDB.mdf','C:\\JavaAndDocker\\DockerDB\\SQLData\\BrandDB_log.ldf']},{'dbName':'ProductDB','dbFiles':['C:\\JavaAndDocker\\DockerDB\\SQLData\\ProductDB.mdf','C:\\JavaAndDocker\\DockerDB\\SQLData\\ProductDB_log.ldf']}]
    ports:
      - '1433:1433'
    volumes:
      - C:\JavaAndDocker\DockerDB\Volumes\POSSQLServer:C:\JavaAndDocker\DockerDB\SqlData
      
networks:
  eservices-sqlserver: